pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/aihoon01/JavaILLab4.git'
            }
        }
        stage('Build') {
            steps {
                bat 'mvnw.cmd clean compile'
            }
        }
        stage('Test') {
            steps {
                bat 'mvnw.cmd test'
            }
        }
        stage('Package') {
            steps {
                bat 'mvnw.cmd package'
            }
        }
    }

    post {
        success {
            echo 'Build, Test, and Packaging were successful!'
        }
        failure {
            echo 'Build failed.'
        }
    }
}
